version: "3.4"

services:
  testbuild:
    build: .

  tree:
    image: matevzfa/nlp-sentiment-analysis:submission
    working_dir: /app
    command: tree
    volumes:
      - data-stanza:/root/stanza_resources
      - data-cache:/app/data/cache
      - data-features:/app/data/features

  preprocessing:
    image: matevzfa/nlp-sentiment-analysis:submission
    working_dir: /app
    command: python -m nlp_code.preprocessing
    volumes:
      - data-stanza:/root/stanza_resources
      - data-cache:/app/data/cache
      - data-features:/app/data/features

  models:
    image: matevzfa/nlp-sentiment-analysis:submission
    working_dir: /app
    command: python -m nlp_code.models
    volumes:
      - data-stanza:/root/stanza_resources
      - data-cache:/app/data/cache
      - data-features:/app/data/features

  models_neural:
    image: matevzfa/nlp-sentiment-analysis:submission
    working_dir: /app
    command: python -m nlp_code.models_neural
    volumes:
      - data-stanza:/root/stanza_resources
      - data-cache:/app/data/cache
      - data-features:/app/data/features

  bert_embeddings:
    image: matevzfa/nlp-sentiment-analysis:submission
    working_dir: /app
    command: python -m nlp_code.bert_embeddings
    volumes:
      - data-stanza:/root/stanza_resources
      - data-cache:/app/data/cache
      - data-features:/app/data/features

  pretrained_bert_embeddings_balanced:
    image: matevzfa/nlp-sentiment-analysis:submission
    working_dir: /app
    command: python -m nlp_code.pretrained_bert_embeddings_balanced
    volumes:
      - data-stanza:/root/stanza_resources
      - data-cache:/app/data/cache
      - data-features:/app/data/features

volumes:
  data-stanza:
  data-cache:
  data-features:
